C.3.2 view course
ianleck/Mentorship-EComm-Backend pull request #140
Opened 2021-03-09 18:14 UTC by kengthong

### Changelog:
- feature: get all sensei courses 
- get course [returns course contracts too depending on the type of user]

## Description:
_Eg; Fixed router bug_
## Checklist:
- [x] Merged latest develop
- [x] PR title makes sense

## Screenshots (where relevant):

2021-03-09 18:27 UTC, ianleck requested changes
Reply comments

2021-03-09 18:27 UTC, ianleck commented on src/controllers/course.controller.ts
> +    console.log('user =', user);
Console log

2021-03-09 18:27 UTC, ianleck commented on src/services/course.service.ts
> +  public static async getOneCourse(courseId: string, user?) {
Actually can I check what is in the { user } object in req

2021-03-09 18:27 UTC, ianleck commented on src/services/course.service.ts
> +          attributes: ['firstName', 'lastName', 'profileImgUrl', 'occupation'],
Do we need to include accountId in case they want to click on him to see his profile

2021-03-09 18:27 UTC, ianleck commented on src/services/course.service.ts
> +          attributes: ['firstName', 'lastName', 'profileImgUrl', 'occupation'],
Same for the other gets

2021-03-09 18:39 UTC, kengthong commented on src/services/course.service.ts
> +  public static async getOneCourse(courseId: string, user?) {
the user from jwt token, maybe i shld pass accountId instead

2021-03-09 18:40 UTC, kengthong commented on src/services/course.service.ts
> +          attributes: ['firstName', 'lastName', 'profileImgUrl', 'occupation'],
course has accountId if im not mistaken

2021-03-10 14:53 UTC, ianleck approved these changes

2021-03-10 14:53 UTC, merged