task-use-cases
ianleck/Mentorship-EComm-Backend pull request #254
Opened 2021-03-28 07:17 UTC by hiixdayah

### Changelog:
## Description:
- Add Task
- Edit Task
- Delete Task
- View task buckets
- View tasks
- View task
## Checklist:
- [x] Merged latest develop
- [x] PR title makes sense

## Screenshots (where relevant):

2021-03-28 07:34 UTC, kengthong requested changes

2021-03-28 07:34 UTC, kengthong commented on src/routes/mentorship.route.ts
> +);
endpt should be '/task/:taskId' no? THere is already this endpt written in your previous PR.

2021-03-28 07:34 UTC, kengthong commented on src/routes/mentorship.route.ts
> +
could you change 'mentorship/task/buckets/...' to maybe 'mentorship/task-bucket/all/:mentorshipContractId'? Cus /task/buckets means like bucket is under task, which is not the case

2021-03-28 07:34 UTC, kengthong commented on src/routes/mentorship.route.ts
> +
so for task it could be mentorship/task-bucket/task or mentorship/task instead

2021-03-28 07:34 UTC, kengthong commented on src/routes/schema/mentorship.schema.ts
> +        attachmentUrl: joi.string().allow('', null),
dont need attachmentURL, it should be updated as an upload or delete attachment call

2021-03-28 07:34 UTC, kengthong commented on src/routes/schema/mentorship.schema.ts
> +        attachmentUrl: joi.string().allow('', null),
same

2021-03-28 07:34 UTC, kengthong commented on src/routes/schema/mentorship.schema.ts
> +        dueAt: joi.string().optional(),
not sure if this should be a joi.date().... instead?

2021-03-28 07:34 UTC, kengthong commented on src/routes/mentorship.route.ts
> +router.get(
When GET task-buckets (plural), it shld be /mentorship/task-bucket/all/:mentorshipContractId. this will return all task buckets JOIN tasks.

When GET one task bucket, it shld bee /mentorship/task-bucket/:taskBucketId.

Probably do not need a /task/:taskbucketid

2021-03-28 07:34 UTC, kengthong commented on src/routes/mentorship.route.ts
> +  '/task/:taskId',
not sure when you would need this since getting a bucket would return all the tasks. Could include if you are sure that the frontend will use this endpt

2021-03-28 07:34 UTC, kengthong commented on src/routes/schema/mentorship.schema.ts
> +        attachmentUrl: joi.string().allow('', null),
which you would have to build too haha

2021-03-28 07:34 UTC, kengthong commented on src/services/mentorship.service.ts
> +    )
could write a function to do all these checks if they are going to be repeated in multiple functions

2021-03-28 07:34 UTC, kengthong commented on src/services/mentorship.service.ts
> +  //====================== TASK =======================
Under get mentorship, could include taskbucket and tasks in the MentorshipContract.findByPk() function.

2021-03-29 06:22 UTC, ianleck approved these changes

2021-03-29 06:36 UTC, kengthong approved these changes

2021-03-29 06:36 UTC, merged