mass-email
ianleck/Mentorship-EComm-Backend pull request #298
Opened 2021-04-04 10:30 UTC by hiixdayah

### Changelog:
## Description:
- Send email to all students when announcement is created
## Checklist:
- [x] Merged latest develop
- [x] PR title makes sense

## Screenshots (where relevant):

2021-04-05 10:15 UTC, kengthong requested changes

2021-04-05 10:15 UTC, kengthong commented on src/controllers/social.controller.ts
> +        });
Can try using the new method from Utility

2021-04-05 10:15 UTC, kengthong commented on src/controllers/user.controller.ts
>            userProfile,
try to standardize the return object key name across the different get user functions.
eg, user vs users vs userProfile vs newUser vs updatedUser. Easier for frontend too. I suggest using just user/newUser/updatedUser

2021-04-05 10:15 UTC, kengthong commented on src/services/user.service.ts
> +        });
why are we returning only accountId for ah?

2021-04-05 10:15 UTC, kengthong commented on src/services/user.service.ts
> +        });
this userProfile const is declared in line 32 too. Does declaring it for a second time throw errors? Did u test the endpt?

2021-04-05 10:15 UTC, kengthong commented on src/services/user.service.ts
> +        const userProfile = await User.findByPk(accountId, {
same as prev

2021-04-06 06:31 UTC, hiixdayah commented on src/services/user.service.ts
> +        });
Lawrence said for now return accountId of the user who blocked

2021-04-06 06:31 UTC, hiixdayah commented on src/services/user.service.ts
> +        const userProfile = await User.findByPk(accountId, {
yup endpoint checked, no errors

2021-04-07 07:27 UTC, kengthong submitted a review, later dismissed

2021-04-07 07:34 UTC, kengthong approved these changes

2021-04-07 07:34 UTC, merged