B56 add refund
ianleck/Mentorship-EComm-Backend pull request #303
Opened 2021-04-08 16:33 UTC by ianleck

### Changelog:
## Description:
- Added `RefundRequest`
- Edited billing to include `mentorPassCount`
- Added `refunded` enum for `BILLING_STATUS`
- Added request refund, approve/reject still needs some work so the routes for those are not up yet. Making the PR first to limit the PR size.
## Checklist:
- [x] Merged latest develop
- [x] PR title makes sense

## Screenshots (where relevant):

2021-04-08 16:40 UTC, ianleck commented on src/services/paypal.service.ts
> +  }
Ignore for now

2021-04-08 19:52 UTC, kengthong requested changes

2021-04-08 19:52 UTC, kengthong commented on src/services/paypal.service.ts
> +      const billing = paidBillings[0];
This looks like a bug right? shld it be const billing = paidBillings[i]

2021-04-08 19:52 UTC, kengthong commented on src/services/paypal.service.ts
> +  }
you didnt include billingId when creating requestRefund but u can query with where billingId in findOne?

2021-04-08 19:52 UTC, kengthong commented on src/models/MentorshipContract.ts
Do you need to add @AfterDestroy to delete related consultations and tasks?

2021-04-09 01:24 UTC, ianleck commented on src/models/MentorshipContract.ts
Not destroying mentorship aft rejection. Anw rejection not done

2021-04-09 02:18 UTC, y1bs commented on src/services/paypal.service.ts
> +    try {
Do you need the billingId for this too?

2021-04-09 03:14 UTC, ianleck commented on src/services/paypal.service.ts
> +  }
Ya can but need use on I've updated it

2021-04-09 04:01 UTC, ianleck commented on src/services/paypal.service.ts
> +    try {
Don't need because if by billingId then mentorpass side will not work. I originally tried with billingId

2021-04-09 04:11 UTC, y1bs commented on src/services/paypal.service.ts
> +    try {
Ahh okok

2021-04-09 04:13 UTC, y1bs approved these changes
Looks ok from the frontend perspective, thanks!

2021-04-09 10:41 UTC, kengthong commented on src/models/MentorshipContract.ts
I was referring to afterDestroy when a mentorshipContract is destroyed, added a new comment bout it

2021-04-09 10:46 UTC, kengthong commented on src/services/paypal.service.ts
> +      });
The afterDestroy comment was actually about this sorry

2021-04-09 11:02 UTC, kengthong approved these changes

2021-04-09 11:02 UTC, merged