send-message
ianleck/Mentorship-EComm-Backend pull request #308
Opened 2021-04-10 07:16 UTC by hiixdayah

### Changelog:
## Description:
- Send Message
- Send Group Message
- View Message between two users
- View Chat List
- Create Chat Group
- Delete Chat Group
- Add User to Chat Group
- Remove User from Chat Group
## Checklist:
- [x] Merged latest develop
- [x] PR title makes sense

## Screenshots (where relevant):

2021-04-10 09:03 UTC, ianleck requested changes
Pls put chat in its own controller etc.

2021-04-11 05:56 UTC, ianleck requested changes
When will you be using `getAllMessages` if `getChatList` seems to fulfil the purpose?

2021-04-11 05:56 UTC, ianleck commented on src/models/ChatGroup.ts
> +  User: User;
what happens if chatgroup creator gets banned, or blocked by user in chatgroup?

2021-04-11 05:56 UTC, ianleck commented on src/models/Message.ts
> +  receiverId: string;
Shouldn't these be not nullable

2021-04-11 05:56 UTC, ianleck commented on src/models/Message.ts
> +  description: string;
can you change this to message or messageBody or content. Description is an inaccurate description of the attribute. Also, not nullable

2021-04-11 05:56 UTC, ianleck commented on src/services/chat.service.ts
> +    var authorized = await this.authorizationCheck(sender, receiver);
don't use var. use let.

2021-04-11 05:56 UTC, ianleck commented on src/services/chat.service.ts
> +    var authorized = await this.authorizationCheck(sender, receiver);
same for all the var in the file

2021-04-11 05:56 UTC, ianleck commented on src/models/Message.ts
> +  receiverId: string;
or at least sender. receiver i see may be nullable for chatgroup

2021-04-11 05:56 UTC, ianleck commented on src/services/chat.service.ts
> +            '$Sender.accountId$': {
does `accountId : {` not work?

2021-04-11 05:56 UTC, ianleck commented on src/services/chat.service.ts
> +    return messages;
doesn't seem to be returning messages for chat groups?

2021-04-11 05:56 UTC, ianleck commented on src/services/chat.service.ts
> +        uniqueIdentifier: identifier,
still don't really see the purpose of uniqueIdentifier being worth the additional lines/checks because it seems to just be a substitute for
`where: {
[Op.or]: [
          { senderId: accountId },
          { receiverId: accountId } ]`

2021-04-11 06:04 UTC, hiixdayah commented on src/services/chat.service.ts
> +        uniqueIdentifier: identifier,
this is done so that i can return FE all the messages sent and received between these two users in one array instead of two arrays of (sent messages and received messages) because it'll be easier for yibs on FE. Because 
where: { [Op.or]: 
    [Op.and] : { [ { senderId: user1Id }, { receiverId: user2Id } ] },
    [Op.and] : { [ { senderId: user2Id }, { receiverId: user1Id } ] }
} 
doesn't work

2021-04-11 07:31 UTC, kengthong commented on src/services/chat.service.ts
> +        authorized = true;
i think instead of authorized = true, can just return true

2021-04-11 07:31 UTC, kengthong commented on src/services/chat.service.ts
> +    }
can just throw this error in authorization check.
means u can just call await this.authorization check without the if statement

2021-04-11 07:31 UTC, kengthong commented on src/services/chat.service.ts
> +  }
This returns an array of messages which im nott sure if FE will be able to sort it into an array of 1-1 chats & chat groups that contains messages. (just imagine sorting this array of messages into the chatlist view in your whatsapp/telegram page)

1. Was thinking could we group the messages by uniqueIndentifier so that it will be able to return an array of messages array (group by unique user pair)
2. Create another table called 'Chat' that is created when a user sends a new message to another user for the first time. Subsequently, we will call Chat.getAll && ChatGroup.getALl then combine this two arrays and sort them by their lastUpdatedDate before returning this combined array to FE.

2021-04-11 07:31 UTC, kengthong commented on src/services/chat.service.ts
> +      );
If the student wants to leave the group (meaning they wanna remove themself from the group), wil the FE still use this endpt? If so, could we add a check to see if the user being removed from the chat is the same user as the one whos making the request? If userToBeDeleted === req.user, authorize it too

2021-04-11 07:31 UTC, kengthong commented on src/services/chat.service.ts
> +  public static async authorizationCheck(sender, receiver) {
as mentioned previously, can just throw the error in this function. This means that other functions callling authorizattion check will not need to check if this.authorizationCheck returns true or false.

2021-04-12 07:45 UTC, kengthong requested changes

2021-04-12 07:45 UTC, kengthong commented on src/routes/chat.route.ts
> +  '/all/chat-list/:accountId',
could just be '/list/:accountId'

2021-04-12 07:45 UTC, kengthong commented on src/models/Chat.ts
> +  @Column(DataType.STRING)
Should add a unique constraint tho its not super impt

2021-04-12 07:45 UTC, kengthong commented on src/services/chat.service.ts
> +    sortByDate(chats);
can add a sortBy 'updatedAt' in the findAll query instead. Got to google that

2021-04-12 07:45 UTC, kengthong commented on src/services/chat.service.ts
> +      identifier = userId.concat(accountId);
Remove these commented code if you are not going to use it

2021-04-12 08:41 UTC, kengthong approved these changes

2021-04-12 08:50 UTC, ianleck approved these changes

2021-04-12 08:50 UTC, merged