E.2.1 video call
ianleck/Mentorship-EComm-Backend pull request #346
Opened 2021-04-15 15:39 UTC by kengthong

### Changelog:
- added socket.ts to accommodate video call
- added additional endpoint to getConsultationById

## Description:
_Eg; Fixed router bug_
## Checklist:
- [ ] Merged latest develop
- [ ] PR title makes sense

## Screenshots (where relevant):

2021-04-15 17:11 UTC, ianleck requested changes

2021-04-15 17:11 UTC, ianleck commented on src/socket.ts
> +           */
still need?

2021-04-16 05:18 UTC, kengthong commented on src/socket.ts
> +           */
its just an eg of how the object look like. shld i remove it?

2021-04-16 05:35 UTC, ianleck approved these changes

2021-04-16 05:35 UTC, merged