c26-reject-student-applications
ianleck/Mentorship-EComm-Backend pull request #57
Opened 2021-03-01 16:30 UTC by hiixdayah

### Changelog:
## Description:
- Completed email sending for accept/reject sensei profile and accept/reject mentorship application
## Checklist:
- [x] Merged latest develop
- [x] PR title makes sense

## Screenshots (where relevant):

2021-03-01 16:43 UTC, ianleck requested changes
See the two comments

2021-03-01 16:43 UTC, ianleck commented on src/services/mentorship.service.ts
> +
Add check if sensei accepting is sensei in mentorshipContract

2021-03-01 16:43 UTC, ianleck commented on src/services/mentorship.service.ts
> +
Same as above

2021-03-02 00:22 UTC, ianleck submitted a review, later dismissed
Put the checks in service layer not controller layer

2021-03-02 00:22 UTC, ianleck commented on src/controllers/mentorship.controller.ts
> +    }
These checks should be in service layer not controller layer since they hit db. We're trying to keep logic in service layer so we know where to look if logic fails.

2021-03-02 02:07 UTC, kengthong approved these changes

2021-03-02 02:08 UTC, merged